version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicatonStop:
    - location: bin/stop_service
      timeout: 10
      runas: root

  BeforeInstall:
    - location: bin/before_install
      timeout: 5000
      runas: root

  AfterInstall:
    - location: bin/install_packages
      timeout: 1200
      runas: root

  ApplicationStart:
    - location: bin/start_service
      timeout: 1200
      runas: root

  ValidateService:
    - location: bin/app_validate
      timeout: 10
      runas: ec2-user